### PR TITLE
Install git-annex and rclone with datalad-installer; enable testing on macOS

### LINKED ISSUE #51: RF github tests to use datalad-installer and test on OSX
Dear @jwodder ,  Now that we have rclone support in datalad-installer, please RF https://github.com/DanielDent/git-annex-remote-rclone/blob/HEAD/.github/workflows/test.yml to

- [ ] install/use datalad-installer to install `git-annex` (latest release alone is ok for now) and `rclone` (versioned)
- [ ] add testing on OSX -- I believe it should work there too

### PR DESCRIPTION
**Pull request by jwodder**
Closes #51.

### CODE REVIEW

**Comment by jwodder** [comment]
@yarikoptic You need to approve running this PR's workflows, but [the run on my fork](https://github.com/jwodder/git-annex-remote-rclone/actions/runs/2502333247) reveals the following problems:

* For version 1.30 of rclone, `rclone --help` exits nonzero, so datalad-installer's end-of-installation test fails.
* Version 1.45 of rclone on macOS requires `rclone config` to be run.

**Comment by yarikoptic** [comment]
uff, travel&covid made me forget about all of this developments.

> You need to approve running this PR's workflows

Hm, I don't see how -- no UI element for that in this PR.  May be I should recreate it off the branch in the main repo, but let's first discuss your observations:

NB @DanielDent would you mind if we add @jwodder to the team? He has been working with me for almost two years and I trust him and his good motivations. @jwodder - would you mind to become part of the team to simplify logistics here?

> For version 1.30 of rclone, rclone --help exits nonzero, so datalad-installer's end-of-installation test fails.

so it is something to probably account for in datalad-installer . Filed https://github.com/datalad/datalad-installer/issues/121

> Version 1.45 of rclone on macOS requires rclone config to be run.

rright. I vaguely remember some `rclone config` required some times but fail to recall details ... may be this what we do in the tests would be sufficient (please add to datalad-installer to do it in some tmpdir if it is):

https://github.com/DanielDent/git-annex-remote-rclone/blob/HEAD/tests/all-in-one.sh#L11

```shell
export HOME=$PWD
echo -e '[local]\ntype = local\nnounc =' > ~/.rclone.conf
```

**Comment by jwodder** [comment]
@yarikoptic 

>> You need to approve running this PR's workflows
>
> Hm, I don't see how -- no UI element for that in this PR.

[Apparently](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks), "workflow runs that have been awaiting approval for more than 30 days are automatically deleted."  I refreshed the commit, so you should see a "2 workflows awaiting approval" message above the merge button and the "This branch has no conflicts with the base branch" message.

**Comment by yarikoptic** [comment]
and I found them now among actions and approved!

**Comment by jwodder** [comment]
@yarikoptic

> rright. I vaguely remember some rclone config required some times but fail to recall details ... may be this what we do in the tests would be sufficient (please add to datalad-installer to do it in some tmpdir if it is):

datalad-installer installs rclone just fine; it's the git-annex-remote-rclone tests that fail due to a lack of `rclone config`.  I thus don't see a reason to add the code to datalad-installer.

Also, the code you linked is already run as part of the tests, yet they still fail with:

```
2022/07/27 22:17:50 NOTICE: Config file "/Users/runner/.config/rclone/rclone.conf" not found - using defaults
2022/07/27 22:17:50 Failed to create file system for "local:/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/dl-Z5pjyAK/rclone-local": didn't find section in config file
```

**Comment by yarikoptic** [comment]
Re rclone config - gotcha! I thought you still had --help invocation by datalad-installer in mind. I will look into that one (we might just skip if anything)

**Comment by yarikoptic** [comment]
Since we did export new HOME pointing to TMPDIR and rclone just decided to ignore it and only in that version and only on OSX:
```
2022/07/27 22:17:50 NOTICE: Config file "/Users/runner/.config/rclone/rclone.conf" not found - using defaults
2022/07/27 22:17:50 Failed to create file system for "local:/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/dl-Z5pjyAK/rclone-local": didn't find section in config file
```
I would consider it to be some bug in rclone to "hardcode HOME logic" which was fixed since then.  @jwodder could you please tune workflow to skip testing on macos-latest, v1.45 ? (I believe we might soon require some later rclone version as minimally supported anyways)

**Comment by jwodder** [comment]
@yarikoptic It looks like rclone 1.45 is simply expecting its config file in a different location (`~/.config/rclone/rclone.conf`) than the one the tests create it in (`~/.rclone.conf`).  See [the rclone documentation](https://rclone.org/docs/#config-config-file) for information on where rclone looks for its config file.

**Comment by yarikoptic** [comment]
then let's see if 6a9fea136b6c1c82aed0190f0f7824caa80bc734 (always using that location in the tests) would be of help here (had to pair into this PR so we know right away if it works for OSX as well... worked fine for me locally for rclone v1.59.0-beta.6202.cfe0911e0)

**Comment by yarikoptic** [comment]
it seems it was not it :
```
+ export HOME=/tmp/dl-VjwggBM
+ HOME=/tmp/dl-VjwggBM
+ mkdir -p /tmp/dl-VjwggBM/.config/rclone
...
2022/07/29 18:00:19 NOTICE: Config file "/home/runner/.config/rclone/rclone.conf" not found - using defaults
```
so those older versions simply do not care about `$HOME` for some reason, reconfirming [my observation above](https://github.com/DanielDent/git-annex-remote-rclone/pull/53#issuecomment-1198298739) about some hardcoded HOME logic.  I will drop that commit since no good.

**Comment by yarikoptic** [comment]
I think it is not worth the fight for 1.45 on OSX -- I will just add a skip there.

**Comment by yarikoptic** [comment]
for 1.30 on OSX -- I filed https://github.com/datalad/datalad-installer/issues/124 .

**Comment by yarikoptic** [comment]
FWIW, excluded both! we have them tested on linux, and soon support of those older would be dropped anyways.

**Comment by yarikoptic** [comment]
viola -- more testing and it is all green! Let's proceed!

**Comment by DanielDent** [comment]
@yarikoptic I am applying the transitive property to trust and have invited @jwodder as a collaborator. Thank you both for your contributions.

**Pull request merged**
