### PR TITLE
Set GITHUB_TOKEN when installing git-annex from datalad/git-annex:release

### PR DESCRIPTION
**Pull request by jwodder**
This should address https://github.com/datalad/datalad-installer/issues/137.

### CODE REVIEW

**Comment by yarikoptic** [comment]
eh, actually I also don't have admin privileges on this repo, so can't set the secret. (can only mege PRs). So let's proceed https://github.com/datalad/datalad-installer/issues/142 way

**Comment by DanielDent** [comment]
Hi -- just happened to see this today, if I can help change a repo setting or add a privilege let me know what you'd like me to do.

**Comment by yarikoptic** [comment]
If you could changev my permissions for this repo to owner, then I could do more good / evil ;-)

**Comment by DanielDent** [comment]
The simplest option I found involved transferring this repo to a new organization, which I have now done. I've also added you both to a maintainers group in said organization, once @yarikoptic accepts the invite. 

Maybe I missed something... that seemed like way more steps than I was expecting to need to take just to grant extra access.

**Comment by yarikoptic** [comment]
I also didn't think it would be needed... Anyways - accepted the invite, thanks for the trust

**Comment by jwodder** [comment]
@yarikoptic Is this PR still needed?

**Comment by yarikoptic** [comment]
probably not -- actions are happy and green, so let's assume that we are good. Thank you @jwodder for the ping.

**Pull request closed without merging**
